# Generated by Django 5.1.1 on 2025-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
