# Generated by Django 5.1.1 on 2024-09-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'placed'), ('PROCESSING', 'processing'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered'), ('PAID', 'paid')], default='PLACED', max_length=10),
        ),
    ]
