# Generated by Django 5.1.1 on 2024-09-20 02:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_account_number', models.CharField(max_length=20, null=True)),
                ('transaction_amount', models.FloatField(validators=[django.core.validators.MaxValueValidator(250000)])),
                ('transaction_currency', models.CharField(choices=[('KES', 'Kenya Shillings')], default='KES', max_length=40)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('wallet', 'Wallet')], default='mpesa', max_length=10)),
                ('transaction_identifier', models.CharField(max_length=255, null=True, unique=True)),
                ('transaction_code', models.CharField(max_length=255, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('purchase', 'Purchase')], max_length=100)),
                ('transaction_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='PROCESSING', max_length=20)),
                ('transaction_initial_response', models.JSONField(blank=True, null=True)),
                ('transaction_callback_response', models.JSONField(blank=True, null=True)),
                ('utilised', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.transaction'),
        ),
    ]
