# Generated by Django 5.1.1 on 2024-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_transaction_order_payment_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
