# Generated by Django 5.1.1 on 2024-11-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rider_vendor_alter_rider_approval_status'),
        ('orders', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.rider'),
        ),
    ]
