# Generated by Django 5.1.1 on 2024-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_notes_order_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PROCESSING', 'Processing'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid')], default='PLACED', max_length=10),
        ),
    ]
