# Generated by Django 5.1.1 on 2024-12-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
