# Generated by Django 5.1.1 on 2026-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_distance_order_delivery_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
