# Generated by Django 5.1.1 on 2026-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_delivery_note_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_client',
            field=models.CharField(choices=[('site', 'Site'), ('pos_web', 'POS Web')], default='site', help_text='Client application that created this order', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('wallet', 'Wallet'), ('cash', 'Cash')], default='mpesa', max_length=10),
        ),
    ]
