# Generated by Django 5.1.1 on 2026-02-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_tax_total_order_total_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_client',
            field=models.CharField(choices=[('web_site', 'Site'), ('pos_web', 'POS Web')], default='web_site', help_text='Client application that created this order', max_length=20),
        ),
    ]
