# Generated by Django 5.1.1 on 2026-07-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverycity_deliverylocation'),
        ('orders', '0017_order_is_guest_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_type',
            field=models.CharField(choices=[('map', 'Map selector'), ('predefined', 'Predefined location'), ('pickup', 'In-store pickup')], default='map', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='predefined_delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliverylocation'),
        ),
    ]
