# Generated by Django 5.1.1 on 2024-11-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RIDER_ACTIVE', 'Active'), ('RIDER_REJECTED', 'Rejected'), ('RIDER_DEACTIVATED', 'Deactivated')], default='PENDING', max_length=255),
        ),
    ]
