# Generated by Django 5.1.1 on 2024-11-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rider_approval_status'),
        ('vendors', '0003_alter_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=255),
        ),
    ]
