# Generated by Django 5.1.1 on 2024-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('LIQUOR', 'liquor'), ('MEAT', 'meat')], default='MEAT', max_length=255),
        ),
    ]
