# Generated by Django 5.1.1 on 2024-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('LIQUOR', 'liquor'), ('MEAT', 'meat')], default='MEAT', max_length=255),
        ),
    ]
