# Generated by Django 5.1.1 on 2024-11-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_total',
            new_name='value',
        ),
    ]
