# Generated by Django 5.1.1 on 2024-11-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_review_total_review_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='review_value',
        ),
    ]
