# Generated by Django 5.1.1 on 2024-11-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_review_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
