# Generated by Django 5.1.1 on 2025-11-04 07:28

from django.db import migrations


def populate_category_types(apps, schema_editor):
    CategoryType = apps.get_model('products', 'CategoryType')

    # Create default category types based on industry choices
    industry_types = [
        ("Food & Beverages", "Food and beverage products"),
        ("Grocery", "General grocery items"),
        ("Butchery", "Meat and butchery products"),
        ("Bakery", "Baked goods and pastries"),
        ("Liquor Store", "Alcoholic beverages"),
        ("Restaurant & Takeaway", "Restaurant and takeaway food"),
        ("Coffee Shop / Café", "Coffee and café products"),
        ("Retail", "General retail products"),
        ("Electronics & Appliances", "Electronic devices and appliances"),
        ("Mobile Phones & Accessories", "Mobile phones and accessories"),
        ("Fashion & Apparel", "Clothing and fashion items"),
        ("Shoes & Footwear", "Shoes and footwear"),
        ("Beauty & Cosmetics", "Beauty and cosmetic products"),
        ("Health & Wellness", "Health and wellness products"),
        ("Pharmacy & Medical Supplies", "Pharmaceutical and medical supplies"),
        ("Home & Living", "Home and living products"),
        ("Furniture & Decor", "Furniture and home décor"),
        ("Hardware & Building Materials", "Hardware and construction materials"),
        ("Automotive & Spare Parts", "Automotive products and spare parts"),
        ("Books & Stationery", "Books and stationery items"),
        ("Toys & Games", "Toys and gaming products"),
        ("Sports & Outdoors", "Sports and outdoor equipment"),
        ("Pet Supplies", "Pet care and supplies"),
        ("Jewelry & Watches", "Jewelry and timepieces"),
        ("Art & Crafts", "Art and craft supplies"),
        ("Baby & Kids", "Baby and children's products"),
        ("Agriculture & Farming", "Agricultural and farming products"),
        ("Services", "Service-based offerings"),
        ("Salon & Spa", "Salon and spa services"),
        ("Cleaning & Laundry", "Cleaning and laundry services"),
        ("Events & Catering", "Event and catering services"),
        ("Technology & IT", "Technology and IT services"),
        ("Education & Training", "Educational and training services"),
        ("Stationery & Office Supplies", "Office and stationery supplies"),
        ("Wholesale & Distribution", "Wholesale and distribution"),
        ("Other", "Other products and services"),
    ]

    for name, description in industry_types:
        CategoryType.objects.get_or_create(
            name=name,
            defaults={'description': description}
        )


def reverse_populate_category_types(apps, schema_editor):
    CategoryType = apps.get_model('products', 'CategoryType')
    CategoryType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20251104_0726'),
    ]

    operations = [
        migrations.RunPython(populate_category_types, reverse_populate_category_types),
    ]
