# Generated by Django 5.1.1 on 2025-11-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20251104_0728'),
    ]

    operations = [
        # Add new foreign key fields temporarily
        migrations.AddField(
            model_name='category',
            name='category_type_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorytype'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorytype'),
        ),
    ]
