# Generated by Django 5.1.1 on 2025-11-04 07:29

from django.db import migrations


def migrate_data_to_new_fields(apps, schema_editor):
    CategoryType = apps.get_model('products', 'CategoryType')
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')

    # Get default category types based on old values
    butchery_type = CategoryType.objects.filter(name="Butchery").first()
    liquor_type = CategoryType.objects.filter(name="Liquor Store").first()
    default_type = CategoryType.objects.filter(name="Food & Beverages").first()

    # Migrate Category data
    for category in Category.objects.all():
        if category.category_type == "MEAT":
            category.category_type_new = butchery_type or default_type
        elif category.category_type == "LIQUOR":
            category.category_type_new = liquor_type or default_type
        else:
            category.category_type_new = default_type
        category.save()

    # Migrate Product data
    for product in Product.objects.all():
        if product.product_type == "MEAT":
            product.product_type_new = butchery_type or default_type
        elif product.product_type == "LIQUOR":
            product.product_type_new = liquor_type or default_type
        else:
            product.product_type_new = default_type
        product.save()


def reverse_migrate_data(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')

    # Clear the new fields
    Category.objects.update(category_type_new=None)
    Product.objects.update(product_type_new=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20251104_0729'),
    ]

    operations = [
        migrations.RunPython(migrate_data_to_new_fields, reverse_migrate_data),
    ]
