# Generated by Django 5.1.1 on 2025-11-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20251104_0729'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        # Rename new fields to original names
        migrations.RenameField(
            model_name='category',
            old_name='category_type_new',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type_new',
            new_name='product_type',
        ),
        # Make fields non-nullable
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorytype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorytype'),
        ),
    ]
