# Generated by Django 5.1.1 on 2026-01-31 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_add_sku_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_includes_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1600000000000000033306690738754696212708950042724609375'), max_digits=5),
        ),
    ]
