# Generated by Django 5.1.1 on 2026-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_price_includes_tax_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
