# Generated by Django 5.1.1 on 2026-01-31 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_is_taxable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(help_text="e.g., 'Standard VAT', 'Reduced Rate'", max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (0.16 for 16%)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Optional description of this tax rate', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default tax rate?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this tax rate active?')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['-is_default', 'rate'],
            },
        ),
    ]
