# Generated by Django 5.1.1 on 2026-02-10 20:06

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Generate unique slugs for all existing products"""
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1

            # Ensure slug is unique
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            product.slug = slug
            product.save()


def reverse_slugs(apps, schema_editor):
    """Remove slugs when reversing migration"""
    Product = apps.get_model('products', 'Product')
    Product.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_taxrate'),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, db_index=True),
        ),
        # Generate slugs for existing products
        migrations.RunPython(generate_slugs, reverse_slugs),
        # Now alter the field to add unique constraint
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, db_index=True),
        ),
    ]
