ORDER_PLACED = "PLACED"
ORDER_PROCESSING ="PROCESSING"
ORDER_IN_TRANSIT ="IN_TRANSIT"
ORDER_DELIVERED ="DELIVERED"
ORDER_CANCELLED ="CANCELLED"
ORDER_PAID ="PAID"

POS_WEB ="pos_web"
WEB_SITE ="web_site"

MPESA ="mpesa"
WALLET ="wallet"
CASH="cash"
