import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import ThemeLayout from "./components/ThemeLayout";


const jost = Jost({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost} antialiased`}
      >
        <ThemeLayout>
          {children}
        </ThemeLayout>
      </body>
    </html>
  );
}
