
USER_TYPE_RIDER = "RIDER"
USER_TYPE_CUSTOMER = "CUSTOMER"
USER_TYPE_BUSINESS_OWNER = "BUSINESS_OWNER"
USER_TYPE_PLATFORM_MANAGER = "PLATFORM_MANAGER"
USER_TYPE_BUSINESS_MANAGER = "BUSINESS_MANAGER"

user_types = (
    (USER_TYPE_RIDER, "Rider"),
    (USER_TYPE_CUSTOMER, "Customer"),
    (USER_TYPE_BUSINESS_MANAGER, "Business Manager"),
    (USER_TYPE_PLATFORM_MANAGER, "Platform Manager"),
    (USER_TYPE_BUSINESS_OWNER, "Business Owner"),
)