# Generated by Django 5.1.1 on 2025-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('primary_color', models.CharField(help_text='Hex code (e.g., #FF5733)', max_length=7)),
                ('secondary_color', models.CharField(help_text='Hex code (e.g., #33C1FF)', max_length=7)),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='site_icons/')),
                ('mpesa_paybill_number', models.CharField(max_length=20)),
                ('fastduka_orgid', models.CharField(max_length=255)),
                ('fastduka_config_id', models.CharField(max_length=255)),
                ('fastduka_api_key', models.CharField(max_length=255)),
                ('google_maps_api_key', models.CharField(max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('match_user_to_closest_vendor', models.BooleanField(default=False)),
            ],
        ),
    ]
