# Generated by Django 5.1.1 on 2025-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
