# Generated by Django 5.1.1 on 2025-04-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_sitesettings_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='test_field',
        ),
    ]
