# Generated by Django 5.1.1 on 2025-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_remove_sitesettings_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logos/'),
        ),
    ]
