# Generated by Django 5.1.1 on 2025-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
