# Generated by Django 5.1.1 on 2025-10-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_sitesettings_footer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
