# Generated by Django 5.1.1 on 2025-10-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_sitesettings_location_sitesettings_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_link',
            field=models.CharField(default='https://store.fastduka.co.ke', max_length=255),
        ),
    ]
