# Generated by Django 5.1.1 on 2025-10-28 08:36

from django.db import migrations


def create_default_sliders(apps, schema_editor):
    HeroSlider = apps.get_model('settings_app', 'HeroSlider')

    default_sliders = [
        {
            'title': 'Savor the flavor, experience the quality',
            'subtitle': 'Premium meats',
            'description': 'Discover our selection of premium quality meats, carefully sourced and prepared to deliver exceptional flavor in every bite.',
            'button_text': 'Shop Now',
            'button_link': '/shop',
            'order': 1,
            'is_active': True,
        },
        {
            'title': 'Your meat, your way',
            'subtitle': 'Customize your order',
            'description': 'Get exactly what you want with our customization options. Choose cuts, portions, and preparation styles that suit your needs.',
            'button_text': 'Customize Order',
            'button_link': '/shop',
            'order': 2,
            'is_active': True,
        },
        {
            'title': 'Cut above the rest.',
            'subtitle': 'Exceptional quality, every time',
            'description': 'We maintain the highest standards in quality and freshness to ensure every purchase exceeds your expectations.',
            'button_text': 'Explore Quality',
            'button_link': '/shop',
            'order': 3,
            'is_active': True,
        },
    ]

    for slider_data in default_sliders:
        HeroSlider.objects.create(**slider_data)


def reverse_default_sliders(apps, schema_editor):
    HeroSlider = apps.get_model('settings_app', 'HeroSlider')
    HeroSlider.objects.filter(
        title__in=[
            'Savor the flavor, experience the quality',
            'Your meat, your way',
            'Cut above the rest.'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_heroslider'),
    ]

    operations = [
        migrations.RunPython(create_default_sliders, reverse_default_sliders),
    ]
