# Generated by Django 5.1.1 on 2025-11-02 19:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_auto_20251028_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF5733', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#33C1FF', image_field=None, max_length=25, samples=None),
        ),
    ]
