# Generated by Django 5.1.1 on 2025-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_alter_sitesettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
