# Generated by Django 5.1.1 on 2025-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0012_sitesettings_logo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_size_desktop',
            field=models.CharField(default='64,64', help_text='Logo size for desktop in pixels: width,height', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_size_mobile',
            field=models.CharField(default='64,64', help_text='Logo size for mobile in pixels: width,height', max_length=20),
        ),
    ]
