# Generated by Django 5.1.1 on 2026-02-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_sitesettings_logo_size_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_menu_structure',
            field=models.JSONField(blank=True, default=list, help_text='Navigation menu structure. See settings_app/constants.py for format.'),
        ),
    ]
