# Generated by Django 5.1.1 on 2026-02-02 11:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0014_sitesettings_top_menu_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_menu_bg',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='top_menu_text_color',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=25, samples=None),
        ),
    ]
