# Generated by Django 5.1.1 on 2026-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0016_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_location_type',
            field=models.CharField(choices=[('map', 'Map selector'), ('predefined', 'Predefined locations')], default='map', max_length=20),
        ),
    ]
