RIDER_PENDING = 'PENDING'
RIDER_ACTIVE = 'ACTIVE'
RIDER_REJECTED = 'REJECTED'
RIDER_DEACTIVATED = 'DEACTIVATED'

RIDER_STATUS_CHOICES =(
    (RIDER_PENDING, 'Pending'),
    (RIDER_ACTIVE, 'Active'),
    (RIDER_REJECTED, 'Rejected'),
    (RIDER_DEACTIVATED, 'Deactivated'),
)

