# Generated by Django 5.1.1 on 2024-12-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendors', '0003_alter_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
