# Generated by Django 5.1.1 on 2025-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='reference_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_ORDER', 'Customer Order'), ('STOCK_ADDITION', 'Stock Addition'), ('ORDER_CANCELLED', 'Cancellation'), ('IN_TRANSIT', 'In Transit'), ('EXPIRY', 'Expiry')], max_length=255, null=True),
        ),
    ]
