# Generated by Django 5.1.1 on 2026-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryhistory_reference_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_ORDER', 'Customer Order'), ('STOCK_ADDITION', 'Stock Addition'), ('STOCK_DEDUCTION', 'Stock Deduction'), ('ORDER_CANCELLED', 'Cancellation'), ('IN_TRANSIT', 'In Transit'), ('EXPIRY', 'Expiry')], max_length=255, null=True),
        ),
    ]
