# Generated by Django 5.1.1 on 2024-11-27 14:39

import django.core.validators
import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorverificationdocument',
            name='document',
            field=models.FileField(help_text='Upload PDF, PNG, or JPEG files (max 10MB)', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']), vendors.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='vendorverificationdocument',
            name='document_type',
            field=models.CharField(choices=[('TAX_PIN_CERTIFICATE', 'Tax Pin'), ('BUSINESS_PERMIT', 'Business Permit')], max_length=255),
        ),
    ]
