# Generated by Django 5.1.1 on 2024-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_radius',
            field=models.FloatField(blank=True, help_text='delivery radius in KM', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
