# Generated by Django 5.1.1 on 2025-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_delivery_radius_vendor_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='verification_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=255),
        ),
    ]
