# Generated by Django 5.1.1 on 2025-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
