# Generated by Django 5.1.1 on 2026-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SHOP_KEEPER', 'SHOP_KEEPER'), ('EDITOR', 'Editor')], default='EDITOR', max_length=255),
        ),
    ]
