
TAX_PIN_CERTIFICATE = 'TAX_PIN_CERTIFICATE'
BUSINESS_PERMIT = 'BUSINESS_PERMIT'

VENDOR_DOCUMENT_TYPES =(
    (TAX_PIN_CERTIFICATE, 'Tax Pin'),
    (BUSINESS_PERMIT, 'Business Permit'),
)

VENDOR_STATUS_APPROVED = 'APPROVED'
VENDOR_STATUS_PENDING = 'PENDING'
VENDOR_STATUS_REJECTED = 'REJECTED'

VENDOR_APPROVAL_STATUS_CHOICES = (
    (VENDOR_STATUS_APPROVED, 'Approved'),
    (VENDOR_STATUS_PENDING, 'Pending'),
    (VENDOR_STATUS_REJECTED, 'Rejected'),
)


VENDOR_ROLE_ADMIN = 'ADMIN'
VENDOR_ROLE_EDITOR = 'EDITOR'

VENDOR_ROLE_CHOICES =(
    (VENDOR_ROLE_ADMIN, 'Admin'),
    (VENDOR_ROLE_EDITOR, 'Editor'),
)

