# Generated by Django 5.1.1 on 2024-11-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('CUSTOMER', 'Customer'), ('BUSINESS_MANAGER', 'Business Manager'), ('PLATFORM_MANAGER', 'Platform Manager'), ('BUSINESS_OWNER', 'Business Owner')], default='CUSTOMER', max_length=255),
        ),
    ]
