# Generated by Django 5.1.1 on 2024-11-27 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_otp_code_user_otp_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid country code (e.g. +254)', regex='^\\+\\d{1,3}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9-10 digits)', regex='^\\d{9,10}$')]),
        ),
    ]
